recommender:
  top_k: 50
  dim: 32
  metric: "angular"
  n_trees: 50
  n_jobs: -1
  search_k: -1
  n_neighbors: 200
paths: 
  user_vectors_path: "data/user_vectors.pkl"
  item_vectors_path: "data/item_vectors.pkl"
  user_map_path: "data/user_mappings.pkl"
  item_map_path: "data/item_mappings.pkl"